import React from "react";
import type { Metadata } from "next";
import { Providers } from "./providers"
import { ColorModeScript } from '@chakra-ui/react'

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode,
}) {
  return (
      <html lang='ko'>
      <body>
      <ColorModeScript initialColorMode='dark'></ColorModeScript>
      <Providers>{children}</Providers>
      </body>
      </html>
  )
}